version: '2.2'
services:
  mysql-container:
    image: mysql
    environment:
        # provide your credentials here
        - MYSQL_ALLOW_EMPTY_PASSWORD=false
        - MYSQL_DATABASE=mysql_demo
        - MYSQL_USER=my_user_name
        - MYSQL_PASSWORD=somethingSecret
    ports:
      - "3306:3306"
    volumes:
      - "D:/Github/python-fast-api:/var/run/mysql"

    networks:
      - lrodriguesNetwork

  redis:
    image: redis
    command: redis-server --requirepass Redis2019!
    ports:
      - "6379:6379"
    networks:
      - lrodriguesNetwork

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - lrodriguesNetwork
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - D:/Github/python-fast-api/data02:/usr/share/elasticsearch/data
    networks:
      - lrodriguesNetwork
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - D:/Github/python-fast-api/data03:/usr/share/elasticsearch/data
    networks:
      - lrodriguesNetwork

  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.1
    links:
      - es01:elasticsearch
    ports:
      - 5601:5601
    # volumes:
    #   - D:/Github/python-fast-api/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - lrodriguesNetwork

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  lrodriguesNetwork:
    driver: bridge
