version: '2.2'
services:
  mysql-container:
    image: mysql
    environment:
        # provide your credentials here
        - MYSQL_ALLOW_EMPTY_PASSWORD=false
        - MYSQL_DATABASE=mysql_demo
        - MYSQL_USER=my_user_name
        - MYSQL_PASSWORD=somethingSecret
    ports:
      - "3306:3306"
    volumes:
      - "D:/Github/python-fast-api:/var/run/mysql"

    networks:
      - lrodriguesNetwork

  redis:
    image: redis
    command: redis-server --requirepass Redis2019!
    ports:
      - "6379:6379"
    networks:
      - lrodriguesNetwork

networks:
  lrodriguesNetwork:
    driver: bridge
